#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const tableSize = 512;
const harmonicBands = [256, 128, 64, 32, 16, 8, 4, 2, 1];
const waveforms = [
  { name: "Triangle", sample: triangle },
  { name: "TriangleSaw", sample: triangleSaw },
  { name: "Saw", sample: saw },
  { name: "Square", sample: (phase, harmonics) => pulse(phase, harmonics, 0.5) },
  { name: "WideRectangle", sample: (phase, harmonics) => pulse(phase, harmonics, 0.625) },
  { name: "NarrowRectangle", sample: (phase, harmonics) => pulse(phase, harmonics, 0.25) }
];

function saw(phase, harmonics) {
  let value = 0;
  for (let harmonic = 1; harmonic <= harmonics; harmonic += 1) {
    value += Math.sin(phase * harmonic) / harmonic;
  }
  return value;
}

function triangle(phase, harmonics) {
  let value = 0;
  for (let harmonic = 1; harmonic <= harmonics; harmonic += 2) {
    const sign = ((harmonic - 1) / 2) % 2 === 0 ? 1 : -1;
    value += sign * Math.sin(phase * harmonic) / (harmonic * harmonic);
  }
  return value;
}

function triangleSaw(phase, harmonics) {
  return (triangle(phase, harmonics) + saw(phase, harmonics)) * 0.5;
}

function pulse(phase, harmonics, dutyCycle) {
  let value = 0;
  for (let harmonic = 1; harmonic <= harmonics; harmonic += 1) {
    const coefficient = 4 * Math.sin(Math.PI * harmonic * dutyCycle) /
      (Math.PI * harmonic);
    value += coefficient * Math.cos(harmonic * phase - Math.PI * harmonic * dutyCycle);
  }
  return value;
}

function normalise(samples) {
  const peak = Math.max(...samples.map((sample) => Math.abs(sample))) || 1;
  return samples.map((sample) => Math.round((sample / peak) * 2047));
}

function renderTable(sample, harmonics) {
  const samples = Array.from({ length: tableSize }, (_, index) =>
    sample((index / tableSize) * Math.PI * 2, harmonics));
  return normalise(samples);
}

function formatValues(values) {
  const rows = [];
  for (let index = 0; index < values.length; index += 12) {
    rows.push(`        ${values.slice(index, index + 12).map((value) =>
      String(value).padStart(6)).join(", ")}`);
  }
  return rows.join(",\n");
}

const header = `#pragma once

#include <stdint.h>

constexpr uint32_t MINIMOOG_WAVE_TABLE_SIZE = ${tableSize}u;
constexpr uint32_t MINIMOOG_WAVE_BAND_COUNT = ${harmonicBands.length}u;
constexpr uint32_t MINIMOOG_WAVE_COUNT = ${waveforms.length}u;

extern const int16_t minimoogWaveLUT[MINIMOOG_WAVE_COUNT]
    [MINIMOOG_WAVE_BAND_COUNT][MINIMOOG_WAVE_TABLE_SIZE];
extern const uint16_t minimoogWaveMaxHarmonics[MINIMOOG_WAVE_BAND_COUNT];
`;

const bands = harmonicBands.map((harmonics) => `    ${harmonics}`).join(",\n");
const tables = waveforms.map(({ name, sample }) => `    { // ${name}
${harmonicBands.map((harmonics) => `      { // ${harmonics} harmonics
${formatValues(renderTable(sample, harmonics))}
      }`).join(",\n")}
    }`).join(",\n");
const source = `// Generated by tools/generate_wavetables.js. Do not hand edit.
#include "MinimoogVoice_WaveLUT.h"

const uint16_t minimoogWaveMaxHarmonics[MINIMOOG_WAVE_BAND_COUNT] = {
${bands}
};

const int16_t minimoogWaveLUT[MINIMOOG_WAVE_COUNT]
    [MINIMOOG_WAVE_BAND_COUNT][MINIMOOG_WAVE_TABLE_SIZE] = {
${tables}
};
`;

const root = path.resolve(__dirname, "..");
fs.writeFileSync(path.join(root, "MinimoogVoice_WaveLUT.h"), header);
fs.writeFileSync(path.join(root, "MinimoogVoice_WaveLUT.cpp"), source);
