#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const tableSize = 512;
const harmonicBands = [256, 128, 64, 32, 16, 8, 4, 2, 1];
const waveforms = [
  { name: "Triangle", sample: triangle },
  { name: "Sharktooth", render: renderSharktoothTable },
  { name: "Saw", sample: saw },
  { name: "Square", sample: (phase, harmonics) => pulse(phase, harmonics, 0.5) },
  { name: "WideRectangle", sample: (phase, harmonics) => pulse(phase, harmonics, 0.625) },
  { name: "NarrowRectangle", sample: (phase, harmonics) => pulse(phase, harmonics, 0.25) }
];

function saw(phase, harmonics) {
  let value = 0;
  for (let harmonic = 1; harmonic <= harmonics; harmonic += 1) {
    value += Math.sin(phase * harmonic) / harmonic;
  }
  return value;
}

function triangle(phase, harmonics) {
  let value = 0;
  for (let harmonic = 1; harmonic <= harmonics; harmonic += 2) {
    const sign = ((harmonic - 1) / 2) % 2 === 0 ? 1 : -1;
    value += sign * Math.sin(phase * harmonic) / (harmonic * harmonic);
  }
  return value;
}

function pulse(phase, harmonics, dutyCycle) {
  let value = 0;
  for (let harmonic = 1; harmonic <= harmonics; harmonic += 1) {
    const coefficient = 4 * Math.sin(Math.PI * harmonic * dutyCycle) /
      (Math.PI * harmonic);
    value += coefficient * Math.cos(harmonic * phase - Math.PI * harmonic * dutyCycle);
  }
  return value;
}

function normalise(samples) {
  const peak = Math.max(...samples.map((sample) => Math.abs(sample))) || 1;
  return samples.map((sample) => Math.round((sample / peak) * 2047));
}

function renderTable(sample, harmonics) {
  const samples = Array.from({ length: tableSize }, (_, index) =>
    sample((index / tableSize) * Math.PI * 2, harmonics));
  return normalise(samples);
}

// The Model D's triangle/sawtooth selection is the discrete "sharktooth"
// waveform, not a control that blends triangle and saw. Define its asymmetric
// triangular source shape once, then derive a band-limited table by retaining
// the requested Fourier partials. The short rise and long fall give it its
// recognisable pointed profile without a sawtooth discontinuity.
const sharktoothHarmonics = buildFourierHarmonics((phase) => {
  const cycle = phase / (Math.PI * 2);
  const peakAt = 0.18;
  return cycle < peakAt
    ? -1 + (2 * cycle) / peakAt
    : 1 - (2 * (cycle - peakAt)) / (1 - peakAt);
});

function buildFourierHarmonics(sample) {
  const analysisSize = 2048;
  const cosine = [];
  const sine = [];
  for (let harmonic = 1; harmonic <= harmonicBands[0]; harmonic += 1) {
    let cosineSum = 0;
    let sineSum = 0;
    for (let index = 0; index < analysisSize; index += 1) {
      const phase = (index / analysisSize) * Math.PI * 2;
      const value = sample(phase);
      cosineSum += value * Math.cos(harmonic * phase);
      sineSum += value * Math.sin(harmonic * phase);
    }
    cosine[harmonic] = (2 * cosineSum) / analysisSize;
    sine[harmonic] = (2 * sineSum) / analysisSize;
  }
  return { cosine, sine };
}

function renderSharktoothTable(harmonics) {
  const samples = Array.from({ length: tableSize }, (_, index) => {
    const phase = (index / tableSize) * Math.PI * 2;
    let value = 0;
    for (let harmonic = 1; harmonic <= harmonics; harmonic += 1) {
      value += sharktoothHarmonics.cosine[harmonic] * Math.cos(harmonic * phase);
      value += sharktoothHarmonics.sine[harmonic] * Math.sin(harmonic * phase);
    }
    return value;
  });
  return normalise(samples);
}

function formatValues(values) {
  const rows = [];
  for (let index = 0; index < values.length; index += 12) {
    rows.push(`        ${values.slice(index, index + 12).map((value) =>
      String(value).padStart(6)).join(", ")}`);
  }
  return rows.join(",\n");
}

const header = `#pragma once

#include <stdint.h>

constexpr uint32_t MINIMOOG_WAVE_TABLE_SIZE = ${tableSize}u;
constexpr uint32_t MINIMOOG_WAVE_BAND_COUNT = ${harmonicBands.length}u;
constexpr uint32_t MINIMOOG_WAVE_COUNT = ${waveforms.length}u;

extern const int16_t minimoogWaveLUT[MINIMOOG_WAVE_COUNT]
    [MINIMOOG_WAVE_BAND_COUNT][MINIMOOG_WAVE_TABLE_SIZE];
extern const uint32_t minimoogWaveMaxFrequency[MINIMOOG_WAVE_BAND_COUNT];
`;

const thresholds = harmonicBands.map((harmonics) =>
  `    ${Math.floor(0x80000000 / harmonics)}u`).join(",\n");
const tables = waveforms.map(({ name, sample, render }) => `    { // ${name}
${harmonicBands.map((harmonics) => `      { // ${harmonics} harmonics
${formatValues(render ? render(harmonics) : renderTable(sample, harmonics))}
      }`).join(",\n")}
    }`).join(",\n");
const source = `// Generated by tools/generate_wavetables.js. Do not hand edit.
#include "MinimoogVoice_WaveLUT.h"

const uint32_t minimoogWaveMaxFrequency[MINIMOOG_WAVE_BAND_COUNT] = {
${thresholds}
};

const int16_t minimoogWaveLUT[MINIMOOG_WAVE_COUNT]
    [MINIMOOG_WAVE_BAND_COUNT][MINIMOOG_WAVE_TABLE_SIZE] = {
${tables}
};
`;

const root = path.resolve(__dirname, "..");
fs.writeFileSync(path.join(root, "MinimoogVoice_WaveLUT.h"), header);
fs.writeFileSync(path.join(root, "MinimoogVoice_WaveLUT.cpp"), source);
